name: ChickenArmy
version: 2.0
main: com.chickenking.army.ChickenArmy
api-version: '1.21'
depend:
  - Citizens

commands:
  chickenarmy:
    description: Spawnt und befehligt deine ChickenArmy.
    aliases: [The_Chickenking]
    usage: /chickenarmy spawn <Anzahl> | attack <Spieler> | tp [NPC-Name]
    permission: chickenking.army

permissions:
  chickenking.army:
    description: Erlaubt das Erstellen einer Chicken-Armee.
    default: op